#!/bin/sh
# Компиллируем и стартуем имеено отсюда, с корня
clear
echo ---START---
echo compile 
javac ./Head.java
javac ./Fields.java
javac ./dbfields.java

echo RUN
echo
java dbfields

echo
echo ---END---
read a
rm *.class
