#!/bin/sh
# Компиллируем и стартуем имеено отсюда, с корня
clear
echo ---START---
echo compile 
# Указываем свой-же каталог для опции -d
#  и javac сама создаст там каталог пакета
javac -g -d ./  ./*.java

echo RUN
echo
# ... для запуска указываем пакет!
java myPacket.testwrite

echo
echo ---END---
read a
